name: deploy-application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout to branch
      uses: actions/checkout@v2
    - name: Building the image
      run: docker build . -t yamatodx/product-demo
    - name: Loggin into Docker Hub
      run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
    - name: Pushing the image to Docker hub
      run: docker push yamatodx/product-demo
# just a comment to trigger
