name: deploy-application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy-application:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: docker build . -t yamatodx/product-demo
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{secrets.DOCKER_USERNAME}} --password-stdin
      - run: docker push yamatodx/product-demo
